### ISSUE TITLE
New battery manager in macOS 10.15.5 not showing

### ISSUE THREAD

**Issue by kecinzer** [kecinzer/hpelitebook850g5-opencore#11]
New battery manager not working...

**Comment by Joaotcs** [comment]
After update, you can't see battery percentage, is that?
Is it from that update or bios update?
Regards

**Comment by kecinzer** [comment]
No, this is new feature in macOS 10.15.5 - battery health manager. But it looks like it not work on hackintoshes.

**Comment by kecinzer** [comment]
This will never to work on hackintosh.
