### ISSUE TITLE
Bad battery life

### ISSUE THREAD

**Issue by kecinzer** [kecinzer/hpelitebook850g5-opencore#17]
I mentioned few days earlier, that I get very bad battery life. I don't know since when this start happening, but I have suspicion about "Massive overhaul".
What is yours battery life?

**Comment by Se7Touch** [comment]
i have elitebook 840 g5 i7 32gb and perfect battery life with this EFI :/

(avg. 6h-8h)

**Comment by Rixxx-git** [comment]
that is a good question. I am on a 830 g5 with this EFI and my battery only holds for about 3 hours.

**Comment by Joaotcs** [comment]
around 6 hours. 830 g5. I have CPUFriend

**Comment by Rixxx-git** [comment]
> around 6 hours. 830 g5. I have CPUFriend

What is CPUFriend and how can I add it to my setup? :)

I use a 830 G5 with @kecinzer's EFI and OC on the latest Catalina and Bios Version.

**Comment by kecinzer** [comment]
I already have CPUFriend in my latest version.

**Comment by Rixxx-git** [comment]
Oh, right. 😄 But I still don't get 6 hours battery life. Do you have anything different @Joaotcs?

**Comment by ghost** [comment]
> i have elitebook 840 g5 i7 32gb and perfect battery life with this EFI :/
> 
> (avg. 6h-8h)


Hey. I have an identical laptop - EliteBook 840 G5 i7 (32Gb RAM) and my battery lasts only about 2-3 hours maximum. But could you share your EFI?

**Comment by Rixxx-git** [comment]
Strange. How can that be? Different battery life with the same laptop and EFI setup?

**Comment by ghost** [comment]
> Strange. How can that be? Different battery life with the same laptop and EFI setup?


I use OpenCore, but since a person on Clover has much better autonomy, because of this I ask you to share your EFI folder

**Comment by Rixxx-git** [comment]
Ah ok. I thought they are all using OpenCore.

**Comment by Rixxx-git** [comment]
unfortunately no help yet. :/ Do you use clover or opencore @Joaotcs ?

**Comment by Joaotcs** [comment]
Opencore, latest bios version, with balance power in bios..

**Comment by Rixxx-git** [comment]
Thank you! I have the latest bios as well. 🙂  What do you mean with balance power?

Which option did you choose?

Click the Battery Health Manager drop-down menu to review the setting options and then select the appropriate setting.

- Let HP manage my battery charging: Use this setting to have the system balance charging between battery health and battery duration. The latest version of the Battery Health Manager dynamically changes how it charges the battery based upon usage conditions and temperature over time.

- Maximize my battery health: Use this setting if the computer stays plugged in to the power adapter most of the time. This setting maximizes battery health by lowering the maximum battery charge level to 80%. The ability to store additional charge in a battery becomes less efficient after 80% and can add additional stress to the battery over time.

- Maximize my battery duration: Use this setting if you need your battery to last as long as possible between charges. The battery charges to 100% to provide maximum run time between charges.

![c06466017](https://user-images.githubusercontent.com/51874661/88564376-6f73f000-d033-11ea-9c59-ae39922003a1.gif)

**Comment by Joaotcs** [comment]
Maximize my battery duration... And all the idle stuff turned on..

**Comment by kecinzer** [comment]
I done some more tweaks but I still get around 5 hours of battery, but it should be around 9 hours. I found setting in BIOS that Turbo boost is turned off on battery, but it was already enabled.
I don’t know what to do next.

**Comment by Rixxx-git** [comment]
same for me

**Comment by kecinzer** [comment]
With SMBus SSDT I can reach 6 hours from real test :). But I think it’s still not enough.

**Comment by Joaotcs** [comment]
That's probably the best we can get... I have seen similar problems before. There is no solution beside what you have already done. You have optimized to the best possible, to my knowledge... Can't recall anything to optimize - maybe disabling Thunderbolt, but you need them. Battery life will always be better on Windows side..

**Comment by kecinzer** [comment]
Ok, I let my college with exactly same model but with Windows 10 do the battery life test. He can't even reach 6 hours of battery life. So I think it's ok.
