### ISSUE TITLE
Hotkeys are unavailable

### ISSUE THREAD

**Issue by wdrich** [kecinzer/hpelitebook850g5-opencore#2]
Hello, when opencore starts osx, the system hotkeys are unavailable. For example, the alt key can bring up the boot menu. Is there any good way?

**Comment by kecinzer** [comment]
It should works, as this parameter is enabled:

<key>PollAppleHotKeys</key>
<true/>

**Comment by wdrich** [comment]
I cannot use the ALT button to bring up the boot menu, PollAppleHotKeys has been set to YES.

**Comment by kecinzer** [comment]
Please refer to OpenCore manual.
