### ISSUE TITLE
Using your EFI Folder

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#20]
Hi buddy,

I just replaced my EFI and SSDT folder with yours and now I get this on startup. 

What did I do wrong? 

Everything was running fine before. I didn't have a SSDT folder before. Just updated to the latest MacOS on my 830 G5 before I changed the folders. 

Thank you for your help! 

![15949861848095734698447426533160](https://user-images.githubusercontent.com/51874661/87782797-77fa4880-c833-11ea-8336-cd7a66917c2c.jpg)

**Comment by Rixxx-git** [comment]
![1594986669158214796464400867840](https://user-images.githubusercontent.com/51874661/87783392-a3c9fe00-c834-11ea-822d-f9ced04109ca.jpg)

**Comment by kecinzer** [comment]
You need to place only content of EFI folder from this repo - OC folder and BOOT folder.
SSDT folder are only decompiled ACPI files.
And from 1st photo it seems you somehow touched config.plist, because I don't have those utilities enabled.

**Comment by Rixxx-git** [comment]
Ah alright. My bad. Thanks for the quick reply!

I replaced your config.plist with mine. Isn't that right?

**Comment by kecinzer** [comment]
> Ah alright. My bad. Thanks for the quick reply!
> 
> I replaced your config.plist with mine. Isn't that right?

No, you need to adopt your configuration, as I changed many files - kexts and also ACPI files.
Your config.plist may pointing to files, that no more exists in current version.

**Comment by Rixxx-git** [comment]
Alright. Thank you!

Which lines of my config file do I have to adopt? :)

**Comment by Rixxx-git** [comment]
I am trying to start from my super-duper backup on an external hard drive but I get the same start menu as before. 

Why is that? 

I am trying to start my former MacOS setup to fix the problem like you said. 

![15949881362039007418398486783132](https://user-images.githubusercontent.com/51874661/87785166-01ac1500-c838-11ea-9ec9-0151b253e31c.jpg)

**Comment by Rixxx-git** [comment]
What do I have to do to be able to fix the problem? :(

**Comment by Rixxx-git** [comment]
got it working again. which lines do I have to change in your config-plist file with my 830 g5? 🙂

**Comment by Rixxx-git** [comment]
all good now. thanks!
