### ISSUE TITLE
AppleALC doesnt load

### ISSUE THREAD

**Issue by Joaotcs** [kecinzer/hpelitebook850g5-opencore#21]
Latest version of AppleALC doesnt load... No audio device after update. Had to rolllback version.

**Comment by kecinzer** [comment]
No problem here. Everything works like a charm.

**Comment by Rixxx-git** [comment]
Everything fine for me as well. Thank for the update, @kecinzer !

**Comment by Joaotcs** [comment]
Strange.. Must be something with my config.plist..
Will use yours and update again

**Comment by Joaotcs** [comment]
Fixed, I cleaned more my config.plist, and it worked now.. Can't really track what particular change made it work, but it now works again with latest kext.
