### ISSUE TITLE
Partly successful with 840g6

### ISSUE THREAD

**Issue by everyb313** [kecinzer/hpelitebook850g5-opencore#22]
@kecinzer: Thanks for your valuable work ! Even a beginner like me was able to modify !

**Changes for 840G6 (CPU i5 8265U, Catalina 10.15.6)**
------------------------------------------------------------------------------------------
**Display** 
device section:
ig-platform-id to 0900A53E
device-id to        A53E0000
ACPI section:
add SSDT-PNLFCF (source github: baohavan/hpelitebook840g6-opencore, otherwise the display brightness is very low)

drawback: cannot change display brightness by F3/F4

**Audio**
device section:
change layout-id to 18

drawback: microphone is displayed in system report /audio but no function (muted ?), Mic mute button F8 opens apple music application

**meanwhile** f found that for microphone a sampling rate of 44100 is set by default (allowed: 44100,48000,96000)
while for loudspeaker a sampling rate of 48000 is set (allowed: 48000,96000)
I think it is quite uncommon to set by default "nonharmonic" sampling rates. But changing microphone with Audio Midi Setup to 48000 didn't help

**No camera** 
(no idea why not)
------------------------------------------------------------------------------------------

Any hints ?
BR everyb313

**Comment by borygo77** [comment]
I got x360 830G6 and same like you mic and camera doesn't work. Removed ssdt-input as those are only remaps done by kecinzer. Brightness keys should work out of the box even with ssd-input. Sometime need to reset EC to get back brightness keys back, just hold power button for 30 sec ;)

**Comment by frax256** [comment]
I can't get it it to run at all on my 840 G6, just gives me a black screen and boots to the next available OS installed.
Any ideas?

**Comment by kecinzer** [comment]
Try to enable bootpicker. As I use only macOS without any other OS, I don't need it.
