### ISSUE TITLE
 The camera is not working

### ISSUE THREAD

**Issue by levsha-me** [kecinzer/hpelitebook850g5-opencore#24]
Hello. I ran into such a problem when using the EFI kecinzer folder, and setting everything up for my system, I still could not start the camera.

![Снимок экрана 2020-08-22 в 02 25 23](https://user-images.githubusercontent.com/68671327/90953289-e4fa9280-e41e-11ea-971a-9b24f9f73a1e.png)
![Снимок экрана 2020-08-22 в 02 26 03](https://user-images.githubusercontent.com/68671327/90953302-f8a5f900-e41e-11ea-82f1-b15608b1d64e.png)

Can someone help me with this problem. I even tried installing Big Sur and all without result

**Comment by Joaotcs** [comment]
Dead end. No chance to make it work. Live with it, change computer, replace webcam, or buy external one..

**Comment by everyb313** [comment]
@Joaotcs: "No chance to make it work"
--> to avoid useless work: what tweaks did you try in order to get the camera into operation ?
same for the microphone: what have you tried ?

**Comment by Joaotcs** [comment]
> @Joaotcs: "No chance to make it work"
> do avoid useless work: which tweaks did you try in order to get the camera into operation ?

You should avoid criticizing others statements when you are unaware of the truth. 
I might not be a software engineer, but I have been on hackintosh world enough to state that fact. You either have one that works out of the box, or make it work with USB patch, or THERE IS NO WAY, to make it work. You can suck it up, or believe in unicorns. There was a 32bits app camera control, that could force camera to work (SOME, not all UVC) but it is dead for a decade, and I haven't seen any replacement of that app.

Cheers

**Comment by Joaotcs** [comment]
About mic, you have to make one layout for your g6.
Don't know how to do it, but that's possible, I just have no knowledge, and ditched the laptop g6 because of multiple incompatibilities

**Comment by ghost** [comment]
> @Joaotcs: "No chance to make it work"
> --> do avoid useless work: what tweaks did you try in order to get the camera into operation ?
> same for the microphone: what have you tried ?

That's the interest. The microphone works as expected. As for the camera, I tried to register it in DeviceProperties as a USB device. But the result is the same. I also tried different kexts regarding universal USB devices.

**Comment by everyb313** [comment]
@Joaotcs 
Sorry, I had no intention to criticize your work. I only wanted to learn what you already tried (w/o success)

**Comment by ghost** [comment]
> @Joaotcs
> Sorry, I had no intention to criticize your work. I only wanted to learn what you already tried (w/o success)

Everything is good. Maybe I didn't put it right. You don’t have any excuse for anything. I want to find a solution to my problem, and if criticism helps in this, then I do not mind)))

**Comment by everyb313** [comment]
@Joaotcs 
to summarize: that means you tried already UVC2FaceTimeHD.kext & FaceTimeHD.kext.zip w/o success ?

**Comment by ghost** [comment]
> @Joaotcs
> to summarize: that means you tried already UVC2FaceTimeHD.kext & FaceTimeHD.kext.zip w/o success ?

Yes, that's right, I've also tried these keksts

**Comment by Joaotcs** [comment]
Oh right, I have read it differently, writing sometimes is tricky. My apologies If I went berserk :). 

His microphone doesn't work because he has G6. You either learn how to make a proper layout (only for experts really) or you just wait for an expert to do that work (that may or may not even come). You you also have to modify ssdt to make hotkeys work on elitebook g6. 
I am just telling you guys, no kexts, no uvc2facetime or anything work. The only thing that could work is going to Mojave or older Mac OS, and open UVC camera control app each time you want to use camera. No other tweak exists (at least for now) to make it work.
Change webcam, laptop or use external webcam. 

That's all you can do, everything else, is useless and you are losing time, like I did before countless times.

**Comment by everyb313** [comment]
Thanks for sharing your experience with me ! That saves a lot of time. cu

(@Joaotcs: I found that I misspelled "**do** avoid useless work"--> should be "**to** avoid useless work".  Sorry for my fault :-(  Please accept my apologies)

**Comment by Joaotcs** [comment]
> Thanks for sharing your experience with me ! That saves a lot of time. cu
> 
> (@Joaotcs: I found that I misspelled "**do** avoid useless work"--> should be "**to** avoid useless work". Sorry for my fault :-( Please accept my apologies)

That's fine 😉

It's sad but it's the truth, I have also bought 3 elitebook g5, only one had working camera. Also bought g6, but I am selling it cuz of audio problems, no hot keys (ex brightness keys), and also non working camera.

I have a few elitebook g5 for sale for 550eur like new. 8350u, but no working camera on Mac os (the one that works I am going to stay with it).
Cheers

**Comment by kecinzer** [comment]
About audio problems - I think you need to found your codec (from Linux DUMP or Windows Device Manager) and correctly assign it - 
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs
It can't be that hard.

**Comment by everyb313** [comment]
Codec dump Ubuntu:

>Codec: Realtek ALC215
>Address: 0
>AFG Function Id: 0x1 (unsol 1)
>Vendor Id: 0x10ec0215
>Subsystem Id: 0x103c854d
>Revision Id: 0x100002
....
The codec already included in acidanthera /AppleALC and I assigned it in the config.plist with layout-id = 18
--> Speaker is listed and ok, microphone is listed but w/o function

The Ubuntu guys also have problems with the microphone of the 840G6.  As far as I can remember, someone fixed it by tweaking some of the keyboard function keys.
My private guess is therefore, that the microphone is muted in OSX by the weird function key mapping.

If someone has a working microphone in the 840G6 I would be glad to get his codec dump.

**Comment by kecinzer** [comment]
@everyb313 according to this - https://github.com/acidanthera/AppleALC/commit/e0eda72188cb0dc5bbf748e3d77bcfc8a6b7e8cf you need to use layout 18. So your ALC215 is supported.
Ah, I don't read fully. I don't know about microphone 😞.

**Comment by everyb313** [comment]
Finally I found a remark in the OC install guide:
"Intel Smart Sound Technology:
    Laptops with Intel SST will not have anything connected through them (usually internal mic) work, as it is not supported. "
