### ISSUE TITLE
eGPU Issue over TB

### ISSUE THREAD

**Issue by cdraggist** [kecinzer/hpelitebook850g5-opencore#25]
Tried adding an eGPU using a Razor Chroma Core X paired with a 5700XT graphics card to this setup and am running into issues. This may be beyond the scope of this Git but wanted to inquire if you had any ideas or if others using this repo are encountering any similar issues. While Thunderbolt is working if plugged in after the device boots this will mount the Razor Chroma X and all of the devices connected but will show the 5700XT as a "Display" under the Graphics/Displays section of System Report. When I try to connect the Razer Chroma Core X before the device boots I receive a kernel panic seemingly from the AMD Radeon Framebuffer. I have included the panic log below, thoughts?

panic(cpu 7 caller 0xffffff801a6469aa): Kernel trap at 0xffffff7f9d953b64, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x000000000000001c, CR3: 0x0000000027b5c000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff80603d0800, RCX: 0x000000000000ffff, RDX: 0x0000000000000001
RSP: 0xffffff83b976bdd0, RBP: 0xffffff83b976bdf0, RSI: 0x0000000000000000, RDI: 0xffffff80603d0800
R8:  0x0000000000000001, R9:  0x0000000000000000, R10: 0xffffff8062cdf9a0, R11: 0xffffff8058b46000
R12: 0xffffff80616de800, R13: 0xffffff806319ee40, R14: 0xffffff8359d8d000, R15: 0xffffff80603d0800
RFL: 0x0000000000010286, RIP: 0xffffff7f9d953b64, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x000000000000001c, Error code: 0x0000000000000000, Fault CPU: 0x7, PL: 0, VF: 1

Backtrace (CPU 7), Frame : Return Address
0xffffff83b976b830 : 0xffffff801a51a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff83b976b880 : 0xffffff801a654a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff83b976b8c0 : 0xffffff801a6465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff83b976b910 : 0xffffff801a4c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff83b976b930 : 0xffffff801a519d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff83b976ba30 : 0xffffff801a51a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff83b976ba80 : 0xffffff801acc1abc mach_kernel : _panic + 0x54
0xffffff83b976baf0 : 0xffffff801a6469aa mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff83b976bc70 : 0xffffff801a6466a8 mach_kernel : _kernel_trap + 0x598
0xffffff83b976bcc0 : 0xffffff801a4c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff83b976bce0 : 0xffffff7f9d953b64 com.apple.kext.AMDRadeonX6000Framebuffer : __ZN14AmdDalServices12uninitializeEv + 0x14
0xffffff83b976bdf0 : 0xffffff7f9d9534fd com.apple.kext.AMDRadeonX6000Framebuffer : __ZN14AmdDalServicesD1Ev + 0x19
0xffffff83b976be10 : 0xffffff7f9d9535d4 com.apple.kext.AMDRadeonX6000Framebuffer : __ZN14AmdDalServicesD0Ev + 0xe
0xffffff83b976be30 : 0xffffff7f9d901487 com.apple.kext.AMDRadeonX6000Framebuffer : __ZN27AMDRadeonX6000_AmdDalHelper4freeEv + 0x1f
0xffffff83b976be50 : 0xffffff7f9d902c0e com.apple.kext.AMDRadeonX6000Framebuffer : __ZN34AMDRadeonX6000_AmdRadeonController4freeEv + 0x9a
0xffffff83b976be70 : 0xffffff801ab952d1 mach_kernel : __ZN7OSArray15flushCollectionEv + 0x51
0xffffff83b976bea0 : 0xffffff801ab950a6 mach_kernel : __ZN7OSArray4freeEv + 0x16
0xffffff83b976bec0 : 0xffffff801abb63ac mach_kernel : __ZN5OSSet4freeEv + 0x1c
0xffffff83b976bee0 : 0xffffff801ac031a4 mach_kernel : __ZN9IOService15terminateWorkerEj + 0xba4
0xffffff83b976bf60 : 0xffffff801ac0d487 mach_kernel : __ZN9IOService15terminateThreadEPvi + 0x97
0xffffff83b976bfa0 : 0xffffff801a4c013e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.kext.AMDRadeonX6000Framebuffer(3.1)[B976989F-24C9-32D6-B993-9113AC2FE350]@0xffffff7f9d8c4000->0xffffff7f9dcf9fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[68557A36-4EE1-372A-983B-BB2769FDB8E0]@0xffffff7f9b645000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[DF219CC1-366A-31FC-B8ED-17C584BA2549]@0xffffff7f9af31000
            dependency: com.apple.iokit.IOGraphicsFamily(576.1)[92A3DAC1-1745-37AC-88DE-FA87B5EB2526]@0xffffff7f9b8f0000
            dependency: com.apple.AppleGraphicsDeviceControl(5.2.6)[372B091D-3A52-3749-AE17-E8A5103D8DB0]@0xffffff7f9bc27000

BSD process name corresponding to current thread: kernel_task
Boot args: -v debug=0x100 keepsyms=1 

Mac OS version:
19G2021

Kernel version:
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
Kernel slide:     0x000000001a200000
Kernel text base: 0xffffff801a400000
__HIB  text base: 0xffffff801a300000
System model name: MacBookPro16,1 (Mac-E1008331FDC96864)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 13299192379

**Comment by kecinzer** [comment]
I don't have any eGPU, co I can't test it. But I see that you use different SMBIOS.
