### ISSUE TITLE
Cannot boot from USB Stick

### ISSUE THREAD

**Issue by ema07cqc** [kecinzer/hpelitebook850g5-opencore#28]
Hi there. Its not an issue I think but i cannot boot from the USB Stick.
EliteBook 840 G5 here. Intel Core i5 8th Gen.
Updated and configured Bios (Q78 Ver 01.12.00) following provided instructions.

Created USB with Catalina Installer (SanDisk Cruzer Blade 16GB) and EFI Partition.
Copied entire EFI folder downloaded from this Git to the EFI Partition in the USB Stick.

When I try to boot from SanDisk USB, nothing happens.

There is a step missing?
Thanks.

![Screen Shot 2020-10-07 at 11 54 04](https://user-images.githubusercontent.com/56570026/95347896-d283cd80-0893-11eb-97cf-cc9058e2b879.png)

![Screen Shot 2020-10-07 at 11 54 53](https://user-images.githubusercontent.com/56570026/95347995-ed564200-0893-11eb-8b42-b121d0c35ca3.png)

![IMG_9919](https://user-images.githubusercontent.com/56570026/95348456-71a8c500-0894-11eb-9cc0-7796292b84be.jpg)

Ive installed other hakintosh in the past, like Mojave using Clover on another EliteBook but i never used OpenCore.
Thank you very much.

**Comment by labrouss** [comment]
Hi,

Try selecting boot from file and then select the usb stick -> efi -> opencore.efi file 

I also have this issue because I also need to press F9 then select boot from file etc ...

**Comment by ema07cqc** [comment]
> Hi,
> 
> Try selecting boot from file and then select the usb stick -> efi -> opencore.efi file
> 
> I also have this issue because I also need to press F9 then select boot from file etc ...

Hi there. Tried that and same result.
With other EFI folders downloaded from Youtube I can get into the GUI but those EFI doesn't work because they are for other models.

**Comment by kecinzer** [comment]
This is weird.
I have one USB stick in FAT32 format withou EFI partition and it works for me also with right structure.
From you screens it looks good to me.
I think it will be some little think.

**Comment by ema07cqc** [comment]
> This is weird.
> I have one USB stick in FAT32 format withou EFI partition and it works for me also with right structure.
> From you screens it looks good to me.
> I think it will be some little think.

Thanks for your reply. Downloaded files again, tried with another USB Stick (EFI partition and simply a FAT partition) and still I cannot get to the GUI. Maybe my EliteBook 840 G5 is different. Model No: 3RF20LT#AC8. Intel Core i5 8250U.
Have a nice day.
