### ISSUE TITLE
thanks for your job

### ISSUE THREAD

**Issue by qybust** [kecinzer/hpelitebook850g5-opencore#3]
My laptop is 830G5,i tried to install 14.6 with your clover efi,failed in expected.Then i find this,hope it's going to be better.

**Comment by Joaotcs** [comment]
What bios version do you have? When I updated to the latest version, my hackintosh stopped working. Had to rollback bios version

**Comment by kasik96** [comment]
This is OpenCore not Clover. This ticket should be closed.
