### ISSUE TITLE
ROM Value - Config.plist

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#31]
I just saw that I run your OpenCore setup without a ROM value in my config.plist

I use my serial number, MBL and UUID but ROM is aAaAaA.

Where do I get my ROM value? Can I still use Clover Configurator to get that value?

Thank you for your help!

**Comment by igorkolesnikov13** [comment]
Hey Rixxx, you can find it in the opencore guide - https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#platforminfo

**Comment by Rixxx-git** [comment]
Thanks! Got it. I use my real mac address now. 🙂
