### ISSUE TITLE
USB Type-C Port

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#33]
Does the USB-C Port on the right side work? 

I would like to use a USB-C to USB 3.0 Adapter to have another USB port. Is that possible? 🙂

**Comment by kecinzer** [comment]
You mean on right side? For me yes. Currently I’m using TB3 dock with many usba and usbc ports without problem.

**Comment by Rixxx-git** [comment]
Yes sorry, on the right side. Thank you! Which dock do you use?

**Comment by kecinzer** [comment]
https://i-tec.pro/en/produkt/tb3cdualdppdx-2/

**Comment by Rixxx-git** [comment]
Thanks!
