### ISSUE TITLE
Big Sur Update

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#36]
Is the update to Big Sur safe for this setup? 🙂

**Comment by piKolin** [comment]
![Captura de pantalla 2020-11-13 a las 9 36 57](https://user-images.githubusercontent.com/3207908/99046962-c9bda000-2593-11eb-80d6-800353a80434.png)
 With this EFI

**Comment by kecinzer** [comment]
I'm running Big Sur until beta months ago. So yes, it's sage :).
It's from this commit - https://github.com/kecinzer/hpelitebook850g5-opencore/commit/7ba42965be3575f6839d14b85f070a61bda82510
