### ISSUE TITLE
Trackpad - VoodooI2C intermittently laggy/non responsive

### ISSUE THREAD

**Issue by lonacluka** [kecinzer/hpelitebook850g5-opencore#37]
Has anybody noticed trackpad multi touch gestures being less responsive somewhat? 
I dont know how to describe but Ill try. If you use virtual desktops and 3-finger gestures to swipe between them I noticed that maybe the first 3 times I swipe it works then the forth time it doesn't work for cca 2secs. Like it ignores all action in this short time period. I will make a video later.

I dont know when I first started noticing this, but I think around Big Sur RC2. I first thought it is in my head but then I booted Catalina latest and noticed issue is non existent there.

EDIT: I will close this issue soon if nobody noticed, and open an issue in VoodooI2c devs repo. Just wanted to hear if anybody else noticed here.

EDIT2: Im on latest non-beta Big Sur 11.0.1 now, forgot to mention.

EDIT3: Just noticed drag-and-drop with trackpad became unstable and almost unusable.

**Comment by kecinzer** [comment]
I will test it and let you know...
Recently I start using Magic Mouse :).

**Comment by kecinzer** [comment]
It works normally for me.

**Comment by lonacluka** [comment]
Thanks for checking out. Now it works for me perfectly. When starts to happen again, after I reboot it works again. I will check the logs.

I will close this.
