### ISSUE TITLE
ROM error on startup

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#38]
Hi guys, I get this error on startup:
OCS: Failed to parse data field as value with type data and <"my mac address"> contents, context <ROM>!

The number in the "my mac address" field is my real mac address from network preferences and I use it as the ROM value in my config.plist. My Mac starts and works fine. I just wanted to know why I get this error and what I can do about it?

Thank you all!

**Comment by kecinzer** [comment]
Please double check you rom address format.

**Comment by Rixxx-git** [comment]
![Screenshot 2020-11-14 at 12 08 17](https://user-images.githubusercontent.com/51874661/99145833-34dda400-2672-11eb-964b-03d0e71f9d7f.jpg)
![Screenshot 2020-11-14 at 12 08 47](https://user-images.githubusercontent.com/51874661/99145834-36a76780-2672-11eb-8daa-150bcb11c531.jpg)

Is the format in my config.plist wrong?

**Comment by labrouss** [comment]
It’s not the MAC address itself. It’s calculated from the MAC. I use clover to calculate SMBIOS values 

Kind regards,
Konstantinos

**Comment by labrouss** [comment]
I mean clover configurator

Kind regards,
Konstantinos

**Comment by Rixxx-git** [comment]
you mean like this?

![Screenshot 2020-11-14 at 19 21 09](https://user-images.githubusercontent.com/51874661/99154256-af2c1980-26ae-11eb-88a1-cb97348452c2.jpg)

I still get the same error with this ROM value

**Comment by Rixxx-git** [comment]
got it. exported the config.plist from clover editor. the rom value has now only 8 characters.

**Comment by labrouss** [comment]
Yes like that ! 

If you are migrating from a CLOVER boot loader you might as well copy the smbios from CLOVER. 

Otherwise generate new SMBIOS settings using clover configurator
