### ISSUE TITLE
Battery Icon doesn't show in Menu Bar / Control Center

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#40]
Hi everybody,
I recognized a few days ago, that the battery icon doesnt show in the menu bar or control center. I enabled both in the settings. The icon has been there after the update to Big Sur, but now I recognized it disappeared.

I use your latest EFI plus Wifi & Bluetoothfirmware kext to use the internal card. My BIOS version is 1.11. or 1.12. I didn't update to the latest version. Might that be the reason or is it a Big Sur issue?

Could also be that it happened after your latest SSDT-EC-USBX update.

Thanks for your help!

**Comment by Axon80** [comment]
Hi,
You need to update your bios to the latest version.

**Comment by Rixxx-git** [comment]
Will there be no other issues when I update the BIOS version on my 830 G5?

**Comment by Axon80** [comment]
The author uses 850 G5 and adapted SSDT for this laptop. You are using the hp 830 G5. I don't know if it will work ..... Maybe you need to go back to the old SSDT ....

**Comment by Rixxx-git** [comment]
@kecinzer What do I have to change about your setup for my 830 G5? 🙂  I think not the bios but the latest ssdt update is the reason.

**Comment by Wizeguy24** [comment]
> @kecinzer What do I have to change about your setup for my 830 G5? 🙂 I think not the bios but the latest ssdt update is the reason.

I had the same issue as you on my 850 G4 - HP released a Bios for mine at the same time as the G5. Updated Bios and all worked perfectly again. I uses Intel Wifi and Bluetooth kexts as well.

**Comment by Rixxx-git** [comment]
Great, thank you! I will try it.

**Comment by Rixxx-git** [comment]
I just updated the BIOS to 1.14. but the icon is still not there. It doesn't even show in the settings sidebar. Only if I search in the settings for "Battery".

![Screenshot 2020-11-22 at 16 02 54](https://user-images.githubusercontent.com/51874661/99907303-60006d00-2cdc-11eb-9386-8f69a9061d6e.jpg)

![Screenshot 2020-11-22 at 16 02 49](https://user-images.githubusercontent.com/51874661/99907280-43fccb80-2cdc-11eb-84c3-cb40c7edb955.jpg)

**Comment by Rixxx-git** [comment]
@Wizeguy24 Now Heliport is not working anymore. I can't turn it on. :(

**Comment by kecinzer** [comment]
May be there are some other differences in 830 G5. Did you updated SSDT-BATT.aml and also patches in config.plist? I changed lot of things according to battery. Mainly ACPI renames and battery ACPI hotpatch.

**Comment by igorkolesnikov13** [comment]
@Rixxx-git, just for your information. I have 840 G5, and after installing the latest BIOS and using the latest config battery is working flawlessly.

**Comment by Rixxx-git** [comment]
Got the battery icon. Forgot to update the config.plist. 

But Heliport is still not working after the update to latest BIOS. @Wizeguy24 I added all 3 kexts and updated config.plist. Any idea? Only ethernet cable is working. Do I have to chance anything about the BIOS settings? Which BIOS settings effect this issue?

@kecinzer Why did you change from Macbook15,4 to 14,1 in config.plist? 🙂

![Screenshot 2020-11-23 at 08 28 05](https://user-images.githubusercontent.com/51874661/99937420-f75dd280-2d65-11eb-8413-8e51d0292129.jpg)

![Screenshot 2020-11-23 at 08 28 15](https://user-images.githubusercontent.com/51874661/99937428-fb89f000-2d65-11eb-8ff3-aa028bbecfc3.jpg)

**Comment by kecinzer** [comment]
@Rixxx-git I'm so sorry, but as I use native Wifi card, I don't support any Intel kexts or drivers. You should ask on that project.

I switched to MacBookPro14,1 according to reading of many threads and also my performance tests. MacBookPro14,1 is better choice in performance. 14,1 also don't have touchbar or touchid.

**Comment by Rixxx-git** [comment]
@kecinzer Don't be sorry! You are doing an awesome job here! 🙂  @Wizeguy24 seems to use your EFI setup, latest BIOS and the Intel kexts. So maybe he can tell me what to do. 🙂

**Comment by Wizeguy24** [comment]
I use the airportitlwm for big sur which uses native wifi controls, no need
for heliport then.

https://github.com/OpenIntelWireless/itlwm/releases

**Comment by Rixxx-git** [comment]
Thanks. I changed itlwm kext to airport kext and changed securebootmodel to default in config.plist like it says in the description. 

Now my laptop doesn't start anymore. Secure boot should stay disabled right? How can I change that again if the laptop doesn't start?

How do I start from my superduper backup on an external hdd? Fast boot turned off, USB boot turned on. Hdd is enabled in boot options and running but nothing happens of startup, after the HP secure boot Logo. 

Any ideas @kecinzer @Wizeguy24 ? 

![1606121971736971427520447442020](https://user-images.githubusercontent.com/51874661/99944082-9be61180-2d72-11eb-8610-3142cb01fe5d.jpg)

**Comment by kecinzer** [comment]
Disable secureboot.

**Comment by Rixxx-git** [comment]
It is disabled in bios settings. How can I disable it again in my config.plist if the laptop doesn't start?

![16061244261453054818437841815716](https://user-images.githubusercontent.com/51874661/99947466-50cefd00-2d78-11eb-8eb7-67a240c3a4d3.jpg)

**Comment by Wizeguy24** [comment]
Boot from usb with EFI on it. Should always have an install usb with EFI
for recovery.

**Comment by Rixxx-git** [comment]
Got it running again. Thanks so much! :)

WiFi is not finding any network and Bluetooth still doesn't show in the settings. I use Bluetooth firmware and inject kext. And it was working before Bios update.

**Comment by Wizeguy24** [comment]
Only 2 options i can think of now is to check for newer version of heliport
and itlwm kext for big sur or post on their github.

**Comment by Rixxx-git** [comment]
@Wizeguy24 Do I have to use itlwm, airportlwm, bluetoothfirmware and injector all together?

**Comment by Rixxx-git** [comment]
@kecinzer You have this in your config.plist: 
				
**<key>Arch</key>
<string>x86_64</string>**

![Screenshot 2020-11-23 at 11 43 43](https://user-images.githubusercontent.com/51874661/99953177-2df51680-2d81-11eb-83c5-8e108819b934.jpg)


When I create a config.plist with my OC folder and ProperTree it creates Arch - Any:

![Screenshot 2020-11-23 at 11 43 12](https://user-images.githubusercontent.com/51874661/99953199-39484200-2d81-11eb-8dbc-fea424a0ecb7.jpg)


Does that make any difference?

**And:** Is the Order of the kexts in config.plist important?

**Comment by Wizeguy24** [comment]
itlwm and heliport go together for wifi or airportlwm only.

Bluetooth files go with either option above.

**Comment by Rixxx-git** [comment]
Strange. itlwm and heli don't work. airportlwm alone doesn't work as well for me.

**Comment by Wizeguy24** [comment]
Are you doing a clean snapshot in propertree or manually adding in ?

**Comment by Rixxx-git** [comment]
I choose "OC Snapshot" and then the OC folder. After that I add the code created in ProperTree to the kext part of the config.plist of @kecinzer. 

Should I use "OC Clean Snapshot"?

Maybe you can show my your config.plist without all the Serial Numbers? 🙂

**Comment by Joaotcs** [comment]
All G5 are the same. Maybe USB ports are different. The rest, is the same!!
Even G4 seems to be compatible....
G6 Audio is different, the rest is also the same.

I think if you solved your problem you can close the topic ;)

**Comment by Rixxx-git** [comment]
> All G5 are the same. Maybe USB ports are different. The rest, is the same!!
> Even G4 seems to be compatible....
> G6 Audio is different, the rest is also the same.
> 
> I think if you solved your problem you can close the topic ;)

Right. The battery problem is solved, but now internal wifi & bluetooth doesn't work anymore.

**Comment by ghost** [comment]
Rixx-git try the alpha relase from itlwm, i only use this one https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0-alpha

**Comment by Rixxx-git** [comment]
> Rixx-git try the alpha relase from itlwm, i only use this one https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0-alpha

Thanks! You use itlwm alpha with Heliport or airportitlwm alpha as standalone?

**Comment by ghost** [comment]
Only airportitlwm 😎

**Comment by Rixxx-git** [comment]
> Only airportitlwm 😎

I added the big sur alpha version but it still can't find any network:

![Screenshot 2020-11-24 at 18 36 36](https://user-images.githubusercontent.com/51874661/100131389-413cda80-2e84-11eb-95ad-03a88eb76202.jpg)

**Comment by Rixxx-git** [comment]
@kecinzer I installed the fenvi wifi card. All working fine now. 🙂 But I changed my EFI to the one from @Joaotcs 
Which part of your EFI do I need to solve the Battery Icon problem? It doesn't show again for me now.

**Comment by Joaotcs** [comment]
My shared EFI is not updated to the latest BIOS, will update today.
Without the latest security modification from kecinzer

**Comment by Joaotcs** [comment]
> @kecinzer I installed the fenvi wifi card. All working fine now. 🙂 But I changed my EFI to the one from @Joaotcs
> Which part of your EFI do I need to solve the Battery Icon problem? It doesn't show again for me now.

Updated now. Please see if it works now ;)
Regards
