### ISSUE TITLE
Authenticated Root is active

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#42]
Since a few days I get this notice, when I run kext updater. Is that right?

![Screenshot 2020-11-25 at 09 12 33](https://user-images.githubusercontent.com/51874661/100200144-7c7bef80-2efe-11eb-9597-cc40f6643dda.jpg)

**Comment by kecinzer** [comment]
What is your current csr-active-config value? I use 00000000, so csrutil is completly enable for full security. I never had issues with it.

**Comment by Rixxx-git** [comment]
I never changed the value. From your setup it has been AAAAAA== all the time. 🙂

**Comment by kecinzer** [comment]
And what is output, when you type "csrutil status" in Terminal?

**Comment by Rixxx-git** [comment]
I set it to the value in the picture and I also tried 000000. But still get the info that root is active. 

Terminal says: System Integrity Protection status: enabled.

![Screenshot 2020-11-25 at 10 40 16](https://user-images.githubusercontent.com/51874661/100209820-9cb1ab80-2f0a-11eb-88ff-47ebaa2c7998.jpg)

**Comment by kecinzer** [comment]
And why you need this?
It seems that app trying to write to unsupported disk.
You have kexts somewhere else than in EFI folder? That is not supported for this project. I updating all kexts regularly.

**Comment by Rixxx-git** [comment]
I don't need it. I was just curious what that root information is about. 🙂 I thought it might be important.
Thank you for your help!
