### ISSUE TITLE
NVRAM reset

### ISSUE THREAD

**Issue by Rixxx-git** [kecinzer/hpelitebook850g5-opencore#44]
Is it safe to reset the NVRAM with our setup? I read about some issues when people do this.

I might have to do it to solve my problem with itlwm kext.

Thanks!

**Comment by kecinzer** [comment]
Yes, I already did it in past few times.

**Comment by Rixxx-git** [comment]
How do I do this?

**Comment by kecinzer** [comment]
It's option in Bootpicker.
