### ISSUE TITLE
Can't find Big Sur install media on OC

### ISSUE THREAD

**Issue by Se7Touch** [kecinzer/hpelitebook850g5-opencore#47]
Hello, I make a new Big Sur install media and copy efi files to flash disk.

I boot laptop from usb and see OC menu but can't find "install macOS" drive...

Have any idea ?

**Comment by kanmissioner** [comment]
Did you format the drive in disk utility?

________________________________

**Comment by Se7Touch** [comment]
Yes, all function is okey with other efi files.

Its problem only this efi..

**Comment by kecinzer** [comment]
Are you following Dortania Guide? I tested Win10 and now I will go back to macOS, so I can let you know how it going.

**Comment by kecinzer** [comment]
Hmm, I created installer on Windows and can’t also see install option in OC. Weird.

**Comment by kecinzer** [comment]
@Se7Touch figured it out. You need to set “ScanPolicy” to 0! Installing right now :).

**Comment by Se7Touch** [comment]
Yes, I fixed the problem but forgot to let you know.  Thank you :)
