### ISSUE TITLE
Start WIN10 restart

### ISSUE THREAD

**Issue by wdrich** [kecinzer/hpelitebook850g5-opencore#5]
Start BOOTCAMP partition WIN10 system restarts repeatedly.
Looking forward to your reply!

**Comment by kecinzer** [comment]
I'm so sorry, but I don't use Windows at all.

**Comment by Joaotcs** [comment]
You should use the boot.efi from windows (using boot menu when your laptop starts). If you enter windows from opencore, it won't work.

**Comment by kasik96** [comment]
Using BootCamp with Hackintosh is not good practice. You should install Win 10 after that Hackintosh and OpenCore will take care of rest after booting. If you didnt really mean BootCamp, and just Dual Boot, maybe your EFI in Windows folder is damaged. Try EFI Windows USB Repair. Also this ticket is not connect to this repo. I suggest this to be closed.
