### ISSUE TITLE
Kernel panic when booting installer on 840 G5

### ISSUE THREAD

**Issue by otaviomad** [kecinzer/hpelitebook850g5-opencore#50]
While trying to boot on my 840 G5 I get an nvme related kernel panic. I've attached a picture of the full logs. I'm using the MacBookPro15,4 SMBIOS.
![image](https://user-images.githubusercontent.com/6334573/106222128-aa5f0800-61bd-11eb-897b-ab69d03414e1.png)

**Comment by otaviomad** [comment]
I've attached a picture of my system specs as declared by speccy

![image](https://user-images.githubusercontent.com/6334573/106279040-9269a180-621a-11eb-99cc-5e6da0f8e38c.png)

**Comment by archfish** [comment]
Replace your ssd device, MTFDHBAXXXTCK was not supported.

**Comment by otaviomad** [comment]
wow, that's unfortunate. thanks for the reply.

**Comment by ammi3** [comment]
> While trying to boot on my 840 G5 I get an nvme related kernel panic. I've attached a picture of the full logs. I'm using the MacBookPro15,4 SMBIOS.
> ![image](https://user-images.githubusercontent.com/6334573/106222128-aa5f0800-61bd-11eb-897b-ab69d03414e1.png)
So, can it work now. My notebook is the same as yours，can you tell me the version of the system you installed and the EFI used. Thank you.

**Comment by spirodelazz** [comment]
> While trying to boot on my 840 G5 I get an nvme related kernel panic. I've attached a picture of the full logs. I'm using the MacBookPro15,4 SMBIOS.
> ![image](https://user-images.githubusercontent.com/6334573/106222128-aa5f0800-61bd-11eb-897b-ab69d03414e1.png)

So, can it work now. My notebook is the same as yours，can you tell me the version of the system you installed and the EFI used. Thank you.

**Comment by otaviomad** [comment]
> So, can it work now. My notebook is the same as yours，can you tell me the version of the system you installed and the EFI used. Thank you.

No, and it probably never will. I just downloaded the EFI from this repo and was trying to install big sur.
